### ISSUE TITLE
Review from Badai

### ISSUE THREAD

**Issue by badaiaqrandista** [Zockleberry/training-AFT16#2]
## ClusterAndInfrastructureSpecifications.adoc

Section "Additional resources"

- URL should not include the marketing tag "?_ga=2.90628888.368479437.1635180877-1652576.1635180877"

https://www.confluent.io/blog/secure-kafka-deployment-best-practices/?_ga=2.90628888.368479437.1635180877-1652576.1635180877

## ClusterSpecificationManagedCluster.adoc

Section "Match the command to the outcome"

- The count of "Commands" and "Outcomes" are different. There is no command for "Displays ingress, egress, storage, provider, region, and status". I think it should be "ccloud kafka cluster describe".

- Also note that "ccloud" command has been deprecated recently and merged with "confluent" CLI v2: https://docs.confluent.io/confluent-cli/current/migrate.html

## MonitoringSpecification.adoc

Section "Validate Monitoring and Observability"

- The following documentation does not explain how to integrate Confluent Platform to DataDog. It merely shows DataDog Sink Connector, which allows you to move DataDog metrics stored in a topic to DataDog. But it does not show you how to monitor CP with DataDog. We got a ticket about this in the past and we told customer that this connector does not allow them to monitor CP with DataDog. We may need to remove this.

```
Integrate with third-party monitoring and log management stacks: https://docs.confluent.io/5.5.0/connect/kafka-connect-datadog-metrics/index.html
```

## NetworkSpecifications.adoc

Section "Challenge your understanding"

- The following link points to a very old version of documentation. Please update it.

```
Develop a networking design that defines the following based on this doc https://docs.confluent.io/5.4.2/installation/operator/co-endpoints.html:
```

## SecuritySpecifications.adoc

Section "Additional resources"

- Please put the links as bullet points. They are currently jumbled together.

**Comment by Zockleberry** [comment]
All issues have been changed and addressed. Ccloud commands have been updated since this will be used throughout 2022
